version: '3.7'
services:
  minio1:
    image: minio/minio:latest
    command: server http://minio{1...4}:9000/data --console-address ":9001"
    container_name: minio1
    environment:
      MINIO_ROOT_USER: t4er-access
      MINIO_ROOT_PASSWORD: t4er-password
    restart: always
    ports:
      - "9101:9000"
      - "9001:9001"
    volumes:
      - /data/minio/minio01:/data
  minio2:
    image: minio/minio:latest
    command: server http://minio{1...4}:9000/data --console-address ":9001"
    container_name: minio2
    environment:
      MINIO_ROOT_USER: t4er-access
      MINIO_ROOT_PASSWORD: t4er-password
    restart: always
    ports:
      - "9102:9000"
    volumes:
      - /data/minio/minio02:/data
  minio3:
    image: minio/minio:latest
    command: server http://minio{1...4}:9000/data --console-address ":9001"
    container_name: minio3
    environment:
      MINIO_ROOT_USER: t4er-access
      MINIO_ROOT_PASSWORD: t4er-password
    restart: always
    ports:
      - "9103:9000"
    volumes:
      - /data/minio/minio03:/data
  minio4:
    image: minio/minio:latest
    command: server http://minio{1...4}:9000/data --console-address ":9001"
    container_name: minio4
    environment:
      MINIO_ROOT_USER: t4er-access
      MINIO_ROOT_PASSWORD: t4er-password
    restart: always
    ports:
      - "9104:9000"
    volumes:
      - /data/minio/minio04:/data