version: '3.7'
services:
  minio1:
    image: minio/minio:latest
    command: server http://minio{1...4}:9000/data --console-address ":9001"
    container_name: minio1
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    restart: always
    ports:
      - "9101:9000"
      - "9001:9001"
    volumes:
      - ./minio1:/data
  minio2:
    image: minio/minio:latest
    command: server http://minio{1...4}:9000/data --console-address ":9001"
    container_name: minio2
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    restart: always
    ports:
      - "9102:9000"
    volumes:
      - ./minio2:/data
  minio3:
    image: minio/minio:latest
    command: server http://minio{1...4}:9000/data --console-address ":9001"
    container_name: minio3
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    restart: always
    ports:
      - "9103:9000"
    volumes:
      - ./minio3:/data
  minio4:
    image: minio/minio:latest
    command: server http://minio{1...4}:9000/data --console-address ":9001"
    container_name: minio4
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    restart: always
    ports:
      - "9104:9000"
    volumes:
      - ./minio4:/data