spring:
  config:
    activate:
      on-profile: prod

  admin-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/admin?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin-t4er
    password: admin-oralng

  user-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC&characterEncoding=UTF-8
    username: user-t4er
    password: user-oralng

  order-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/orderr?serverTimezone=UTC&characterEncoding=UTF-8
    username: order-t4er
    password: order-oralng

  pay-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/pay?serverTimezone=UTC&characterEncoding=UTF-8
    username: pay-t4er
    password: pay-oralng

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false