apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  db_root_password: <base64-encoded-root-password>
  db_user: <base64-encoded-user>
  db_user_password: <base64-encoded-password>
