version: "3.7"

services:
  user-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=user-t4er
      - MYSQL_PASSWORD=user-oralng
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci