spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?serverTimezone=UTC&characterEncoding=UTF-8
    username: order-t4er
    password: order-oralng

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false