version: "3.7"

services:
  order-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=order
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=order-t4er
      - MYSQL_PASSWORD=order-oralng
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci