version: "3.7"

services:
  master:
    image: redis:latest
    container_name: redis-master
    networks:
      - redis
    volumes:
      - ./data/master:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - "6379"

  sentinel1:
    image: redis:latest
    container_name: redis-sentinel1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - redis
    depends_on:
      - master
    expose:
      - "26379"

  sentinel2:
    image: redis:latest
    container_name: redis-sentinel2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - redis
    depends_on:
      - master
    expose:
      - "26379"

  sentinel3:
    image: redis:latest
    container_name: redis-sentinel3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - redis
    depends_on:
      - master
    expose:
      - "26379"

networks:
  redis:
    driver: bridge
