version: "3.7"

services:
  pay-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=pay
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=pay-t4er
      - MYSQL_PASSWORD=pay-oralng
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci