spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ORALNG
    username: root
    password: root

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mariadb://localhost:3306/ORALNG
    user: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace