spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ORALNG
    username: root
    password: root

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false