version: "3.7"

services:
  admin-db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=admin-t4er
      - MYSQL_PASSWORD=admin-oralng
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci