name: BackEnd_Build_Test

on:
  pull_request:
    branches:
      - develop
    types: opened

defaults:
  run:
    working-directory: ./oralngoralng-back

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.id, 4130469453)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Test
        run: ./gradlew bootJar